# Generated by Django 3.0.2 on 2020-01-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='workout date')),
                ('preworkout_scoops', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('weight_in_pounds', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_splits.WorkoutDay')),
            ],
        ),
    ]
