# Generated by Django 3.0.2 on 2020-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutday',
            name='workout_day',
            field=models.CharField(choices=[('Chest', 'Chest Day'), ('Legs', 'Leg Day'), ('Shoulders', 'Shoulder Day'), ('Back', 'Back Day')], default='Chest', max_length=10),
        ),
    ]
