# Generated by Django 3.0.2 on 2020-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0002_workoutday_workout_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='bar_type',
            field=models.CharField(choices=[('bb', 'Barbel'), ('db', 'Dumbell')], default='bb', max_length=2),
        ),
    ]
