# Generated by Django 3.0.2 on 2020-01-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0007_auto_20200112_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='bar_type',
            field=models.CharField(choices=[('bb', 'Barbel'), ('db', 'Dumbell'), ('bw', 'Bodyweight'), ('m', 'Machine')], default='bb', max_length=2),
        ),
    ]
