# Generated by Django 3.0.2 on 2020-01-13 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0008_auto_20200112_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
