# Generated by Django 3.0.2 on 2020-01-17 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0012_remove_set_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
