# Generated by Django 3.0.2 on 2020-01-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0013_set_set_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_number',
        ),
    ]
