# Generated by Django 3.0.2 on 2020-02-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_splits', '0014_remove_set_set_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='added_note',
        ),
    ]
